/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudentIndexRouteImport } from './routes/_authenticated/student/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedStudentRoomsRouteImport } from './routes/_authenticated/student/rooms'
import { Route as AuthenticatedStudentHistoryRouteImport } from './routes/_authenticated/student/history'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminReservationsRouteImport } from './routes/_authenticated/admin/reservations'
import { Route as AuthenticatedAdminRoomsIndexRouteImport } from './routes/_authenticated/admin/rooms/index'
import { Route as AuthenticatedAdminRoomsCreateRouteImport } from './routes/_authenticated/admin/rooms/create'
import { Route as AuthenticatedAdminRoomsRoomIdEditRouteImport } from './routes/_authenticated/admin/rooms/$roomId.edit'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudentIndexRoute =
  AuthenticatedStudentIndexRouteImport.update({
    id: '/student/',
    path: '/student/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentRoomsRoute =
  AuthenticatedStudentRoomsRouteImport.update({
    id: '/student/rooms',
    path: '/student/rooms',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudentHistoryRoute =
  AuthenticatedStudentHistoryRouteImport.update({
    id: '/student/history',
    path: '/student/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminReservationsRoute =
  AuthenticatedAdminReservationsRouteImport.update({
    id: '/admin/reservations',
    path: '/admin/reservations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoomsIndexRoute =
  AuthenticatedAdminRoomsIndexRouteImport.update({
    id: '/admin/rooms/',
    path: '/admin/rooms/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoomsCreateRoute =
  AuthenticatedAdminRoomsCreateRouteImport.update({
    id: '/admin/rooms/create',
    path: '/admin/rooms/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRoomsRoomIdEditRoute =
  AuthenticatedAdminRoomsRoomIdEditRouteImport.update({
    id: '/admin/rooms/$roomId/edit',
    path: '/admin/rooms/$roomId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/student/history': typeof AuthenticatedStudentHistoryRoute
  '/student/rooms': typeof AuthenticatedStudentRoomsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/admin/rooms/create': typeof AuthenticatedAdminRoomsCreateRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsIndexRoute
  '/admin/rooms/$roomId/edit': typeof AuthenticatedAdminRoomsRoomIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/student/history': typeof AuthenticatedStudentHistoryRoute
  '/student/rooms': typeof AuthenticatedStudentRoomsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/student': typeof AuthenticatedStudentIndexRoute
  '/admin/rooms/create': typeof AuthenticatedAdminRoomsCreateRoute
  '/admin/rooms': typeof AuthenticatedAdminRoomsIndexRoute
  '/admin/rooms/$roomId/edit': typeof AuthenticatedAdminRoomsRoomIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/services': typeof ServicesRoute
  '/_authenticated/admin/reservations': typeof AuthenticatedAdminReservationsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/student/history': typeof AuthenticatedStudentHistoryRoute
  '/_authenticated/student/rooms': typeof AuthenticatedStudentRoomsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/student/': typeof AuthenticatedStudentIndexRoute
  '/_authenticated/admin/rooms/create': typeof AuthenticatedAdminRoomsCreateRoute
  '/_authenticated/admin/rooms/': typeof AuthenticatedAdminRoomsIndexRoute
  '/_authenticated/admin/rooms/$roomId/edit': typeof AuthenticatedAdminRoomsRoomIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/services'
    | '/admin/reservations'
    | '/admin/users'
    | '/student/history'
    | '/student/rooms'
    | '/admin'
    | '/student'
    | '/admin/rooms/create'
    | '/admin/rooms'
    | '/admin/rooms/$roomId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/services'
    | '/admin/reservations'
    | '/admin/users'
    | '/student/history'
    | '/student/rooms'
    | '/admin'
    | '/student'
    | '/admin/rooms/create'
    | '/admin/rooms'
    | '/admin/rooms/$roomId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/login'
    | '/services'
    | '/_authenticated/admin/reservations'
    | '/_authenticated/admin/users'
    | '/_authenticated/student/history'
    | '/_authenticated/student/rooms'
    | '/_authenticated/admin/'
    | '/_authenticated/student/'
    | '/_authenticated/admin/rooms/create'
    | '/_authenticated/admin/rooms/'
    | '/_authenticated/admin/rooms/$roomId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  ServicesRoute: typeof ServicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/student/': {
      id: '/_authenticated/student/'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/rooms': {
      id: '/_authenticated/student/rooms'
      path: '/student/rooms'
      fullPath: '/student/rooms'
      preLoaderRoute: typeof AuthenticatedStudentRoomsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student/history': {
      id: '/_authenticated/student/history'
      path: '/student/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof AuthenticatedStudentHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/reservations': {
      id: '/_authenticated/admin/reservations'
      path: '/admin/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AuthenticatedAdminReservationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/rooms/': {
      id: '/_authenticated/admin/rooms/'
      path: '/admin/rooms'
      fullPath: '/admin/rooms'
      preLoaderRoute: typeof AuthenticatedAdminRoomsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/rooms/create': {
      id: '/_authenticated/admin/rooms/create'
      path: '/admin/rooms/create'
      fullPath: '/admin/rooms/create'
      preLoaderRoute: typeof AuthenticatedAdminRoomsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/rooms/$roomId/edit': {
      id: '/_authenticated/admin/rooms/$roomId/edit'
      path: '/admin/rooms/$roomId/edit'
      fullPath: '/admin/rooms/$roomId/edit'
      preLoaderRoute: typeof AuthenticatedAdminRoomsRoomIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminReservationsRoute: typeof AuthenticatedAdminReservationsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedStudentHistoryRoute: typeof AuthenticatedStudentHistoryRoute
  AuthenticatedStudentRoomsRoute: typeof AuthenticatedStudentRoomsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedStudentIndexRoute: typeof AuthenticatedStudentIndexRoute
  AuthenticatedAdminRoomsCreateRoute: typeof AuthenticatedAdminRoomsCreateRoute
  AuthenticatedAdminRoomsIndexRoute: typeof AuthenticatedAdminRoomsIndexRoute
  AuthenticatedAdminRoomsRoomIdEditRoute: typeof AuthenticatedAdminRoomsRoomIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminReservationsRoute: AuthenticatedAdminReservationsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedStudentHistoryRoute: AuthenticatedStudentHistoryRoute,
  AuthenticatedStudentRoomsRoute: AuthenticatedStudentRoomsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedStudentIndexRoute: AuthenticatedStudentIndexRoute,
  AuthenticatedAdminRoomsCreateRoute: AuthenticatedAdminRoomsCreateRoute,
  AuthenticatedAdminRoomsIndexRoute: AuthenticatedAdminRoomsIndexRoute,
  AuthenticatedAdminRoomsRoomIdEditRoute:
    AuthenticatedAdminRoomsRoomIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  ServicesRoute: ServicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
